### PR TITLE
Finish the documentation for package cobweb3d.core.*

### PR DESCRIPTION
**Pull request by ZewenShen**
Would you please have a look at whether or not my document follows the required style? This time I did a pull request only for few documents, in order to make sure it satisfies your requirements.

### CODE REVIEW

**Comment by ychenwang** [comment]
I would suggest cleaning up stuff like "I don't know what this does" before merging this. The reminders also do not exactly inspire confidence.

**Comment by COBWEB** [comment]
Zewen
I have sent your examples to one of our programmers from last year, who you
will meet in the fall.

Brad Bass, PhD

**Comment by ZewenShen** [comment]
@ychenwang But I have to make sure no one will be misled by me lol Do you have any advice?

**Comment by ZewenShen** [comment]
@COBWEB Thank you!

**Comment by COBWEB** [comment]
Don't do any more changes to the document until we here from Adam. However, it will probably be okay. I will explain in another email. Brad Bass, Phd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: ZewenSent: Monday, June 25, 2018 1:34 AMTo: COBWEB-ca/cobweb3dReply To: COBWEB-ca/cobweb3dCc: COBWEB; CommentSubject: Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)@ychenwang But I have to make sure no one will be misled by me lol Do you have any advice?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb3d","title":"COBWEB-ca/cobweb3d","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Walden-Shen in #1: @ychenwang But I have to make sure no one will be misled by me lol Do you have any advice?"}],"action":{"name":"View Pull Request","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Zewen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Walden-Shen",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"pullRequestId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349438515\n}"
}
],
"themeColor": "26292E"
}

**Comment by AdamAdli** [comment]
**Thoughts**
While I appreciate the time you are putting into documentation I strongly suggest you refrain from using personal language. A lot of the comments take up more space than the help they provide.

I can provide you with some guidelines, suggestions, and constructive criticisms; however I think your changes need to be edited before we merge your pull request.

**Issues / Constructive Criticism**
First year computer science courses tend to put a greater emphasis on documentation rather than actual coding its self, which would probably give you unrealistic expectations on how to move forward with a project. 

Do not use "I" nor sentences like "this is a well written class..." nor "Reminder: I am not the author". 

As you work on COBWEB I recommend you embrace the principle that **"Less is more"**. 

**Example: Direction class**
We do not require any real documentation for the class Direction, and if we do, it should really be 1 sentence. 

```
**
 * This is a subclass of Vector3i, which is a well-written vector class in R^3.
 * Class Direction uses the orthonormal basis of R^3 to indicate the direction of any agents.
 *
 * Document Author: Zewen Shen
 * Reminder: I'm not the author of this class, so my document may be inaccurate.
 */ 
```
1. "Well-written" has no place here - it really provides no technical information and is unprofessional. Avoid artistic language.
2. Who is to say that Direction will only be used for agents in the future? 
3. "Reminder: I'm not the author of this class.." - is really unnecessary and unprofessional sounding.
4. Unless it really is a big contribution that you have made like a set of classes for a plugin I suggest you don't put your name as an author of a class.  I did not put my name in the code because many of the classes have been re-used with modification from other programmers work. 

Since it is so self-explanatory and more a data structure than class no one ever decided to write documentation. If I were to, I would probably write the following documentation instead.
```
**
 * Sub-class of Vector3i that represents an orthonormal direction in R^3.
 */
```

**Next Steps**
Agreeing with @ychenwang, please clean up your changes and ensure they meet the professional standards. It's in the best interest to not merge the current pull request.

**Comment by COBWEB** [comment]
AdamThank you for reviewing and instructing Zewen. He is extremely enthusiastic, but I have asked him to stop until I could let you look at his initial work. However, I still need to channel his enthusiasm. RegardsBrad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: AdamAdliSent: Monday, June 25, 2018 1:48 PMTo: COBWEB-ca/cobweb3dReply To: COBWEB-ca/cobweb3dCc: COBWEB; MentionSubject: Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)Thoughts
While I appreciate the time you are putting into documentation I strongly suggest you refrain from using personal language. A lot of the comments take up more space than the help they provide.
I can provide you with some guidelines, suggestions, and constructive criticisms; however I think your changes need to be edited before we merge your pull request.
Issues / Constructive Criticism
First year computer science courses tend to put a greater emphasis on documentation rather than actual coding its self, which would probably give you unrealistic expectations on how to move forward with a project.
Do not use "I" nor sentences like "this is a well written class..." nor "Reminder: I am not the author".
As you work on COBWEB I recommend you embrace the principle that "Less is more".
Example: Direction class
We do not require any real documentation for the class Direction, and if we do, it should really be 1 sentence.
**
 * This is a subclass of Vector3i, which is a well-written vector class in R^3.
 * Class Direction uses the orthonormal basis of R^3 to indicate the direction of any agents.
 *
 * Document Author: Zewen Shen
 * Reminder: I'm not the author of this class, so my document may be inaccurate.
 */ 


"Well-written" has no place here - it really provides no technical information and is unprofessional. Avoid artistic language.
Who is to say that Direction will only be used for agents in the future?
"Reminder: I'm not the author of this class.." - is really unnecessary and unprofessional sounding.
Unless it really is a big contribution that you have made like a set of classes for a plugin I suggest you don't put your name as an author of a class.  I did not put my name in the code because many of the classes have been re-used with modification from other programmers work.

Since it is so self-explanatory and more a data structure than class no one ever decided to write documentation. If I were to, I would probably write the following documentation instead.
**
 * Sub-class of Vector3i that represents an orthonormal direction in R^3.
 */

Next Steps
Agreeing with @ychenwang, please clean up your changes and ensure they meet the professional standards. It's in the best interest to not merge the current pull request.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400037632","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400037632","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb3d","title":"COBWEB-ca/cobweb3d","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AdamAdli in #1: **Thoughts**\r\nWhile I appreciate the time you are putting into documentation I strongly suggest you refrain from using personal language. A lot of the comments take up more space than the help they provide.\r\n\r\nI can provide you with some guidelines, suggestions, and constructive criticisms; however I think your changes need to be edited before we merge your pull request.\r\n\r\n**Issues / Constructive Criticism**\r\nFirst year computer science courses tend to put a greater emphasis on documentation rather than actual coding its self, which would probably give you unrealistic expectations on how to move forward with a project. \r\n\r\nDo not use \"I\" nor sentences like \"this is a well written class...\" nor \"Reminder: I am not the author\". \r\n\r\nAs you work on COBWEB I recommend you embrace the principle that **\"Less is more\"**. \r\n\r\n**Example: Direction class**\r\nWe do not require any real documentation for the class Direction, and if we do, it should really be 1 sentence. \r\n\r\n```\r\n**\r\n * This is a subclass of Vector3i, which is a well-written vector class in R^3.\r\n * Class Direction uses the orthonormal basis of R^3 to indicate the direction of any agents.\r\n *\r\n * Document Author: Zewen Shen\r\n * Reminder: I'm not the author of this class, so my document may be inaccurate.\r\n */ \r\n```\r\n1. \"Well-written\" has no place here - it really provides no technical information and is unprofessional. Avoid artistic language.\r\n2. Who is to say that Direction will only be used for agents in the future? \r\n3. \"Reminder: I'm not the author of this class..\" - is really unnecessary and unprofessional sounding.\r\n4. Unless it really is a big contribution that you have made like a set of classes for a plugin I suggest you don't put your name as an author of a class.  I did not put my name in the code because many of the classes have been re-used with modification from other programmers work. \r\n\r\nSince it is so self-explanatory and more a data structure than class no one ever decided to write documentation. If I were to, I would probably write the following documentation instead.\r\n```\r\n**\r\n * Sub-class of Vector3i that represents an orthonormal direction in R^3.\r\n */\r\n```\r\n\r\n**Next Steps**\r\nAgreeing with @ychenwang, please clean up your changes and ensure they meet the professional standards. It's in the best interest to not merge the current pull request."}],"action":{"name":"View Pull Request","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400037632"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)",
"sections": [
{
"text": "",
"activityTitle": "**AdamAdli**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AdamAdli",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"pullRequestId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400037632"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349438515\n}"
}
],
"themeColor": "26292E"
}

**Comment by COBWEB** [comment]
ZewenAdam has provided some good comments. I appreciate your enthusiasm to document the code. Please treat Adam's comments as constructive criticism. It is not meant to dampen your enthusiasm. However, please follow his guidelines for documentation. I will discuss your AI questions in a reply to that email Brad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: ZewenSent: Monday, June 25, 2018 1:34 AMTo: COBWEB-ca/cobweb3dReply To: COBWEB-ca/cobweb3dCc: COBWEB; CommentSubject: Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)@ychenwang But I have to make sure no one will be misled by me lol Do you have any advice?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb3d","title":"COBWEB-ca/cobweb3d","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Walden-Shen in #1: @ychenwang But I have to make sure no one will be misled by me lol Do you have any advice?"}],"action":{"name":"View Pull Request","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Zewen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Walden-Shen",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"pullRequestId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-399836826"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349438515\n}"
}
],
"themeColor": "26292E"
}

**Comment by AdamAdli** [comment]
It definitely is useful to have more documentation and definitely help with understanding the project - rather the issue is the approach. @Walden-Shen please ask me for any advice moving forward; you have my contact details.

If @COBWEB would like these changes applied right now, we can do it. 

However I strongly suggest the comments are trimmed out and polished before we merge.

**Comment by COBWEB** [comment]
AdamI agree with you. Let Zewen Polish his comments, then we can see how he handled the revisions. Brad                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: AdamAdliSent: Monday, June 25, 2018 1:55 PMTo: COBWEB-ca/cobweb3dReply To: COBWEB-ca/cobweb3dCc: COBWEB; MentionSubject: Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)It definitely is useful to have more documentation and definitely help with understanding the project - rather the issue is the approach. @Walden-Shen please ask me for any advice moving forward; you have my contact details.
If @COBWEB would like these changes applied right now, we can do it.
However I strongly suggest the comments are trimmed out and polished before we merge.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400039833","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400039833","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/COBWEB-ca/cobweb3d","title":"COBWEB-ca/cobweb3d","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/COBWEB-ca/cobweb3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AdamAdli in #1: It definitely is useful to have more documentation and definitely help with understanding the project - rather the issue is the approach. @Walden-Shen please ask me for any advice moving forward; you have my contact details.\r\n\r\nIf @COBWEB would like these changes applied right now, we can do it. \r\n\r\nHowever I strongly suggest the comments are trimmed out and polished before we merge."}],"action":{"name":"View Pull Request","url":"https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400039833"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [COBWEB-ca/cobweb3d] Finish the document for package cobweb3d.core.* (#1)",
"sections": [
{
"text": "",
"activityTitle": "**AdamAdli**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AdamAdli",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"COBWEB-ca/cobweb3d\",\n\"pullRequestId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/COBWEB-ca/cobweb3d/pull/1#issuecomment-400039833"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 349438515\n}"
}
],
"themeColor": "26292E"
}

**Comment by ZewenShen** [comment]
Adam’s advice makes sense! I will fix them according to that later

**Pull request merged**
